#!/usr/bin/env python3
"""Time one RTL design in two simulators: Icarus Verilog (event-driven, interpreted) and
Verilator (cycle-based, compiled to C++). Writes results.json / results.md next to this file.

    RTL_COSIM=~/Claude_sandbox/RTL_CoSim_NTT  ~/Claude_sandbox/RTL_CoSim_NTT/.venv/bin/python run_rtl_speed.py
    (source ~/.local/opt/verilator-deb/env.sh first; run it alone, memory-capped)

The design is ntt_core (W = 50, N = 1024, P = 4 lanes) from RTL_CoSim_NTT; the inputs, twiddles
and the golden NTT come from that repo's Python model, and the testbench checks every output word.
Wall time is the simulation run only (compilation is reported separately), best of three.
"""
import json
import os
import random
import re
import shutil
import subprocess
import time
from pathlib import Path

from ntt_cosim.model import barrett_mu, find_psi, ntt_primes, ntt_reference, twiddles

HERE = Path(__file__).resolve().parent
RTL = Path(os.environ.get("RTL_COSIM", Path.home() / "Claude_sandbox/RTL_CoSim_NTT")) / "rtl"
SRC = [str(RTL / f) for f in ("mod_mul_barrett.sv", "ntt_butterfly.sv", "ntt_core.sv")] + [str(HERE / "tb_ntt_speed.sv")]
W, LOGN = 50, 10
N = 1 << LOGN
REPS = {"icarus": int(os.environ.get("REPS_ICARUS", 20)), "verilator": int(os.environ.get("REPS_VERILATOR", 2000))}


def hexfile(name, vals, digits):
    (BUILD / name).write_text("\n".join(f"{v:0{digits}x}" for v in vals) + "\n")


def run(cmd, cwd):
    t0 = time.perf_counter()
    p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    dt = time.perf_counter() - t0
    if p.returncode:
        raise SystemExit(f"{' '.join(cmd)} failed:\n{p.stdout}\n{p.stderr}")
    return dt, p.stdout


def version(cmd):
    return subprocess.run(cmd, capture_output=True, text=True).stdout.splitlines()[0].strip()


BUILD = HERE / "build"
if __name__ == "__main__":
    shutil.rmtree(BUILD, ignore_errors=True)
    BUILD.mkdir()
    q = ntt_primes(W, 2 * N, 1)[0]
    w = find_psi(q, N)
    rng = random.Random(1)
    x = [rng.randrange(q) for _ in range(N)]
    hexfile("cfg_q.hex", [q], 13)
    hexfile("cfg_mu.hex", [barrett_mu(q, W)], 13)
    hexfile("tw.hex", twiddles(q, w, N // 2), 13)
    hexfile("x.hex", x, 13)
    hexfile("want.hex", ntt_reference(x, q, w), 13)
    rows = []
    for sim in ("icarus", "verilator"):
        reps = REPS[sim]
        if sim == "icarus":
            comp, _ = run(["iverilog", "-g2012", f"-Ptb_ntt_speed.REPS={reps}", "-o", "sim_icarus", *SRC], BUILD)
            cmd = ["vvp", "-n", "sim_icarus"]
            ver = version(["iverilog", "-V"])
        else:
            comp, _ = run(["verilator", "--binary", "--timing", "-j", "2", "-Wno-fatal", "--top-module", "tb_ntt_speed",
                           f"-GREPS={reps}", "-o", "sim_verilator", *SRC], BUILD)
            cmd = ["obj_dir/sim_verilator"]
            ver = version(["verilator", "--version"])
        times = []
        for _ in range(3):
            dt, out = run(cmd, BUILD)
            times.append(dt)
        m = re.search(r"REPS=(\d+) CYCLES=(\d+) ERRORS=(\d+)", out)
        reps, cycles, errors = map(int, m.groups())
        assert errors == 0, f"{sim}: {errors} output words differ from the golden NTT"
        best = min(times)
        rows.append(dict(sim=sim, version=ver, transforms=reps, cycles=cycles, compile_s=round(comp, 2),
                         run_s=round(best, 3), cycles_per_s=round(cycles / best)))
    (HERE / "results.json").write_text(json.dumps(rows, indent=1) + "\n")
    ratio = rows[1]["cycles_per_s"] / rows[0]["cycles_per_s"]
    md = ["# RTL simulation speed: event-driven against cycle-based", "",
          "Generated by `run_rtl_speed.py` on the build machine (Intel i7-3770, 15 GB RAM). Design: `ntt_core` from",
          "[RTL_CoSim_NTT](https://github.com/BrendanJamesLynskey/RTL_CoSim_NTT) with W = 50, N = 1024, P = 4.",
          "Every output word was checked against the golden NTT; zero mismatches. Run time is the best of three.", "",
          "| Simulator | Version | Transforms | Clock cycles | Compile (s) | Run (s) | Cycles per second |",
          "|---|---|---|---|---|---|---|"]
    for r in rows:
        md.append(f"| {r['sim']} | {r['version']} | {r['transforms']} | {r['cycles']:,} | {r['compile_s']} | {r['run_s']} | {r['cycles_per_s']:,} |")
    md += ["", f"Verilator simulated {ratio:.0f}× more clock cycles per second than Icarus on this design."]
    (HERE / "results.md").write_text("\n".join(md) + "\n")
    print("\n".join(md))
