#!/usr/bin/env python3
"""Time a system-level discrete-event simulation: Disaggregated_Inference_Sim (SimPy) serving
3,000 Llama-3-70B requests at 4 req/s with its default configuration, event by event and with its
exact fast path (macro-stepped decode). Counts SimPy events by wrapping Environment.step.
Writes results.json / results.md next to this file.

    ~/Claude_sandbox/Rust_DES_Kernel/.venv/bin/python run_des_speed.py   (any venv with disagg_sim)
"""
import json
import time
from dataclasses import replace
from pathlib import Path

import simpy
from disagg_sim import cli, sim as S
from disagg_sim.workload import LengthDist, poisson_workload

HERE = Path(__file__).resolve().parent
ARGS = ["--requests", "3000", "--rate", "4", "--seed", "1"]

count = {"n": 0}
_step = simpy.Environment.step


def counting_step(self):
    count["n"] += 1
    return _step(self)


simpy.Environment.step = counting_step

rows = []
for fast in (False, True):
    a = cli.build_parser().parse_args(ARGS)
    cfg = replace(cli.config_from_args(a), fast_forward=fast)
    best = None
    for _ in range(3):
        wl = poisson_workload(a.rate, a.requests, LengthDist(a.prompt, a.prompt_cv),
                              LengthDist(a.output, a.output_cv), seed=a.seed)
        count["n"] = 0
        t0 = time.perf_counter()
        res = S.simulate(cfg, wl)
        dt = time.perf_counter() - t0
        sim_s = res.horizon
        if best is None or dt < best[0]:
            best = (dt, count["n"], sim_s)
    dt, events, sim_s = best
    rows.append(dict(fast_path=fast, requests=3000, events=events, simulated_s=round(sim_s, 1), wall_s=round(dt, 3),
                     events_per_s=round(events / dt), sim_s_per_wall_s=round(sim_s / dt, 1)))

(HERE / "results.json").write_text(json.dumps(rows, indent=1) + "\n")
md = ["# System-level DES speed: an LLM-serving simulator", "",
      "Generated by `run_des_speed.py` on the build machine (Intel i7-3770). Model:",
      "[Disaggregated_Inference_Sim](https://github.com/BrendanJamesLynskey/Disaggregated_Inference_Sim)",
      "(SimPy), default configuration, `" + " ".join(ARGS) + "`. Wall time is the simulation only, best of three.", "",
      "| Decode modelling | SimPy events | Simulated time (s) | Wall time (s) | Events per second | Simulated seconds per wall second |",
      "|---|---|---|---|---|---|"]
for r in rows:
    md.append(f"| {'exact fast path (macro-stepped)' if r['fast_path'] else 'one event per decode step'} | {r['events']:,} | "
              f"{r['simulated_s']:,} | {r['wall_s']} | {r['events_per_s']:,} | {r['sim_s_per_wall_s']:,} |")
(HERE / "results.md").write_text("\n".join(md) + "\n")
print("\n".join(md))
